<div class="col-md-12 col-12 mb-3">
    <div class="form-group">
        <label for="clothes_brand" class="form-label">{{ __('الماركة') }}</label>
        <select name="clothes_brand" id="clothes_brand" class="form-select">
            <option value='{{__("H&M")}}'>{{__("H&M")}}</option>
            <option value='{{__("آن تايلور")}}'>{{__("آن تايلور")}}</option>
            <option value='{{__("أميريكان ايجل")}}'>{{__("أميريكان ايجل")}}</option>
            <option value='{{__("أويشو")}}'>{{__("أويشو")}}</option>
            <option value='{{__("اديداس")}}'>{{__("اديداس")}}</option>
            <option value='{{__("ال سي وايكيكي")}}'>{{__("ال سي وايكيكي")}}</option>
            <option value='{{__("اوكسو")}}'>{{__("اوكسو")}}</option>
            <option value='{{__("اولد نيفي")}}'>{{__("اولد نيفي")}}</option>
            <option value='{{__("بانانا ريبوبليك")}}'>{{__("بانانا ريبوبليك")}}</option>
            <option value='{{__("بانجايا")}}'>{{__("بانجايا")}}</option>
            <option value='{{__("برومود")}}'>{{__("برومود")}}</option>
            <option value='{{__("بوجي")}}'>{{__("بوجي")}}</option>
            <option value='{{__("بول اند بير")}}'>{{__("بول اند بير")}}</option>
            <option value='{{__("بولو")}}'>{{__("بولو")}}</option>
            <option value='{{__("بوما")}}'>{{__("بوما")}}</option>
            <option value='{{__("بيبي")}}'>{{__("بيبي")}}</option>
            <option value='{{__("بيرشكا")}}'>{{__("بيرشكا")}}</option>
            <option value='{{__("تشامبيون")}}'>{{__("تشامبيون")}}</option>
            <option value='{{__("تشيكو")}}'>{{__("تشيكو")}}</option>
            <option value='{{__("تومي هيلفيغر")}}'>{{__("تومي هيلفيغر")}}</option>
            <option value='{{__("جاب")}}'>{{__("جاب")}}</option>
            <option value='{{__("جيس")}}'>{{__("جيس")}}</option>
            <option value='{{__("دابنهامز")}}'>{{__("دابنهامز")}}</option>
            <option value='{{__("رالف لورين")}}'>{{__("رالف لورين")}}</option>
            <option value='{{__("ريبوك")}}'>{{__("ريبوك")}}</option>
            <option value='{{__("زارا")}}'>{{__("زارا")}}</option>
            <option value='{{__("سانتا باربارا بولو")}}'>{{__("سانتا باربارا بولو")}}</option>
            <option value='{{__("سبيريت")}}'>{{__("سبيريت")}}</option>
            <option value='{{__("ستراديفاريوس")}}'>{{__("ستراديفاريوس")}}</option>
            <option value='{{__("فري لوك")}}'>{{__("فري لوك")}}</option>
            <option value='{{__("فندي")}}'>{{__("فندي")}}</option>
            <option value='{{__("فورايفر 21")}}'>{{__("فورايفر 21")}}</option>
            <option value='{{__("فيرو مودا")}}'>{{__("فيرو مودا")}}</option>
            <option value='{{__("فيكتوريا سيكريت")}}'>{{__("فيكتوريا سيكريت")}}</option>
            <option value='{{__("كاروليتا")}}'>{{__("كاروليتا")}}</option>
            <option value='{{__("كارين ميللين")}}'>{{__("كارين ميللين")}}</option>
            <option value='{{__("كالزيدونيا")}}'>{{__("كالزيدونيا")}}</option>
            <option value='{{__("كالفن كلاين")}}'>{{__("كالفن كلاين")}}</option>
            <option value='{{__("كوتون")}}'>{{__("كوتون")}}</option>
            <option value='{{__("كوليزيوني")}}'>{{__("كوليزيوني")}}</option>
            <option value='{{__("كولينز")}}'>{{__("كولينز")}}</option>
            <option value='{{__("كويز")}}'>{{__("كويز")}}</option>
            <option value='{{__("لا في اون روز")}}'>{{__("لا في اون روز")}}</option>
            <option value='{{__("ليفي")}}'>{{__("ليفي")}}</option>
            <option value='{{__("ماتلان")}}'>{{__("ماتلان")}}</option>
            <option value='{{__("ماسيمو دوتي")}}'>{{__("ماسيمو دوتي")}}</option>
            <option value='{{__("ماكس")}}'>{{__("ماكس")}}</option>
            <option value='{{__("مانجو")}}'>{{__("مانجو")}}</option>
            <option value='{{__("مودا نوفا")}}'>{{__("مودا نوفا")}}</option>
            <option value='{{__("مونسون")}}'>{{__("مونسون")}}</option>
            <option value='{{__("نايكي")}}'>{{__("نايكي")}}</option>
            <option value='{{__("نيكست")}}'>{{__("نيكست")}}</option>
            <option value='{{__("أخرى")}}'>{{__("أخرى")}}</option>
        </select>
    </div>
</div>
