<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $fillable = [
        'url',
        'title',
        'title2',
        'meta',
        'tags',
        'intro',
        'emailadmin',
        'mobileadmin',
        'smtp',
        'smtpport',
        'ssltls',
        'emailresponse',
        'passwordemailresponse',
        'copyright',
        'description',
        'msgclose',
        'header',
        'footer',
        'msgaddproductstatus',
        'msgaddproduct',
        'msgactivationmobile',
        'advice',
        'ipapi',
        'timeadnoregister',
        'timeadregister',
        'numberadsspecialuser',
        'conditionnumberadsspecialuser',
        'anonymousad',
        'showadanonymous',
        'showadusers',
        'showstoreusers',
        'showcomments',
        'removecommentonlyspecial',
        'republishspecialonly',
        'allowfilter',
        'allowslider',
        'allowmobilepack',
        'allowsms',
        'apn',
        'apnuser',
        'apnpassword',
        'apnname',
        'forceactivatemobile',
        'nbrtentativemobile',
        'nbrfreesms',
        'nbrcategoriesmobile',
        'forceactivateemail',
        'allowcash',
        'commission',
        'commissionvalue',
        'googlemapskey',
        'instagram',
        'facebook',
        'twitter',
        'googleplay',
        'appstore',
        'loginsocialmedia',
        'paymentgateways',
        'enabletags',
        'recaptcha',
        'recaptchasitekey',
        'recaptchasecretkey',
    ];
    use HasFactory;
}
